Fix/Issue 162 Infinite loop with non-editable block inside toggle
kommitters/editorjs-toggle-block pull request #169
Opened 2022-11-14 20:54 UTC by karolrojas07

Closes #162 

# Solution
![162](https://user-images.githubusercontent.com/100703669/201762842-3b9badbe-8906-4284-9924-ab0e1abb2d4f.gif)

2022-11-15 17:03 UTC, miguelnietoa requested changes
Hello @karolrojas07, thanks a lot for solving the issue!! 😄 💯 

Some changes are required ⬇️

2022-11-15 19:24 UTC, karolrojas07 commented on src/index.js
> +  }
Awesome!, I didn't know I can check if the object exists using Boolean class. This is so much better and compact. Thank you.

2022-11-15 19:25 UTC, karolrojas07 commented on src/index.js
> +  */
Done!

2022-11-15 19:52 UTC, karolrojas07 commented on test/testHelpers.js
> +}
This has been refactored. Thank you!

2022-11-15 20:18 UTC, karolrojas07 commented on test/testHelpers.js
> +}
Done!

2022-11-15 20:22 UTC, miguelnietoa commented
Thank you for submitting the changes! @karolrojas07 
In order to merge this change we need you to sign the commit. See https://docs.github.com/es/authentication/managing-commit-signature-verification/about-commit-signature-verification

2022-11-15 23:27 UTC, miguelnietoa commented
@karolrojas07 only the bundle.js file needs to be updated by running the command `npm run build`

2022-11-16 16:34 UTC, miguelnietoa approved these changes
🚀

2022-11-16 16:35 UTC, merged