34 - Implement method to destroy full toggle
kommitters/editorjs-toggle-block pull request #39
Opened 2022-03-17 22:03 UTC by juliansg022

Developing #34, which is required to destroy the toggle and the blocks inside it when the root is deleted with 'backspace', and when the 'delete block' button through the block settings (native EditorJS element) is clicked.

2022-03-18 22:54 UTC, juliansg022 commented
Hello @juanhurtado10, @MarioRodriguezS, and @jcamilocp. This PR closes #34.

An event was added in the delete button (toolbar block) to delete the blocks inside the toggle at the same time that the toggle root is deleted.

Also, the event was added to execute it when the backspace key is typed in the toggle root and this is empty.

This image shows the behaviors previously explained:
![Animation](https://user-images.githubusercontent.com/50778235/159094504-aa75c911-8b72-4161-88d8-02751b611952.gif)

2022-03-18 23:06 UTC, juanhurtado10 requested changes
@juliansg022 LGTM 🚀 !! What about the tests?

2022-03-18 23:09 UTC, juliansg022 commented
> @juliansg022 LGTM 🚀 !! What about the tests?

@juanhurtado10 You're right, the tests to these events are missing. I'll work on them.

2022-03-21 17:57 UTC, juanhurtado10 approved these changes

2022-03-21 18:58 UTC, merged